### PR TITLE
added Germany North region

### PR DESCRIPTION
**Pull request by jurajsucik**

### CODE REVIEW

**Comment by richorama** [comment]
Thank you! I’m currently away on vacation. I’ll get to this as soon as I can.

**Comment by jurajsucik** [comment]
OK, waiting for your approval. I would like to some more regions in the near future. Expect more pull requests :)

**Comment by jurajsucik** [comment]
@richorama, please could you have a look?

**Comment by richorama** [comment]
thank you - and sorry for the delay, I was touring new zealand without a computer :¬)

**Pull request merged**
